local anim8 = require "lib.utils.anim8"

--- @class SpriteBehavior : Behavior
--- @field animationTable table<string, table>
--- @field animationGrid table
--- @field manifest table
--- @field sheets table
--- @field state "idle"|"run"|"hurt"|"attack"
--- @field side 1|-1
local sprite = {}
sprite.__index = sprite
sprite.id = "sprite"
sprite.LEFT = -1
sprite.RIGHT = 1
--- Скорость между кадрами в анимации
sprite.ANIMATION_SPEED = 0.1

function sprite.new(spriteDir)
    local anim = setmetatable({}, sprite)
    anim.animationTable = {}
    anim.animationGrid = {}
    anim.manifest = spriteDir.manifest
    anim.sheets = spriteDir.sheets
    -- n: name; i: image
    for n, i in pairs(spriteDir.sheets) do
        local aGrid = anim8.newGrid(anim.manifest.width, anim.manifest.height, i:getWidth(), i:getHeight())
        local tiles = '1-' .. math.ceil(i:getWidth() / anim.manifest.width)
        anim.animationGrid[n] = aGrid(tiles, 1)
    end

    anim.state = "idle"
    anim.side = sprite.RIGHT
    anim:loop("idle")
    return anim
end

function sprite:update(dt)
    local anim = self.animationTable[self.state] or self.animationTable["idle"] or nil

    if not anim then return end
    anim:update(dt)
end

function sprite:draw()
    if not self.animationTable[self.state] or not self.sheets[self.state] then return end

    self.owner:try(Tree.behaviors.positioned,
        function(pos)
            local ppm = Tree.level.camera.pixelsPerMeter
            local position = pos.position + Vec3 { 0.5, 0.5 }

            Tree.level.render:enqueue(Tree.level.render.LAYERS.SPRITE, position.y, function()
                love.graphics.setColor(1, 1, 1)
                if Tree.level.selector.id == self.owner.id then
                    local texW, texH = self.sheets[self.state]:getWidth(),
                        self.sheets[self.state]:getHeight()
                    local shader = Tree.assets.files.shaders.outline
                    shader:send("texSize", { texW, texH })
                    shader:send("time", love.timer:getTime())
                    love.graphics.setShader(shader)
                end
                self.animationTable[self.state]:draw(self.sheets[self.state],
                    position.x,
                    position.y, nil, 1 / ppm * self.side, 1 / ppm, self.manifest.base.x, self.manifest.base.y)

                love.graphics.setShader()
            end)
        end
    )
end

--- @return Task<nil>
function sprite:animate(state)
    return function(callback)
        if not self.animationGrid[state] then
            print("[SpriteBehavior]: no animation for '" .. state .. "'")
            return callback()
        end
        self.animationTable[state] = anim8.newAnimation(self.animationGrid[state], self.ANIMATION_SPEED,
            function()
                self:loop("idle")
                callback()
            end)
        self.state = state
    end
end

function sprite:loop(state)
    if not self.animationGrid[state] then
        return print("[SpriteBehavior]: no animation for '" .. state .. "'")
    end
    self.animationTable[state] = anim8.newAnimation(self.animationGrid[state], self.ANIMATION_SPEED)
    if state == 'idle' then
        self.animationTable[state]:gotoFrame(love.math.random(#self.animationTable[state].frames))
    end
    self.state = state
end

return sprite
